<?php

namespace Taleez\Model;

class JobProfileTypeEnum
{
    const COMPTABILITE = 'COMPTABILITE';
    const ADMINISTRATION = 'ADMINISTRATION';
    const ART_ET_DESIGN = 'ART_ET_DESIGN';
    const DEVELOPPEMENT_COMMERCIAL = 'DEVELOPPEMENT_COMMERCIAL';
    const SERVICE_A_LA_COMMUNAUTE_ET_SOCIAL = 'SERVICE_A_LA_COMMUNAUTE_ET_SOCIAL';
    const CONSEIL = 'CONSEIL';
    const ENSEIGNEMENT = 'ENSEIGNEMENT';
    const INGENIERIE = 'INGENIERIE';
    const ENTREPRENARIAT = 'ENTREPRENARIAT';
    const FINANCE = 'FINANCE';
    const SERVICE_DE_SANTE = 'SERVICE_DE_SANTE';
    const RESSOURCES_HUMAINES = 'RESSOURCES_HUMAINES';
    const TECHNOLOGIES_DE_LINFORMATION = 'TECHNOLOGIES_DE_LINFORMATION';
    const SERVICE_JURIDIQUE = 'SERVICE_JURIDIQUE';
    const MARKETING = 'MARKETING';
    const MEDIAS_ET_COMMUNICATION = 'MEDIAS_ET_COMMUNICATION';
    const OPERATIONS = 'OPERATIONS';
    const RESPONSABLE_PRODUIT = 'RESPONSABLE_PRODUIT';
    const MANAGEMENT_DE_PROJET = 'MANAGEMENT_DE_PROJET';
    const ACHATS = 'ACHATS';
    const CONTROLE_QUALITE = 'CONTROLE_QUALITE';
    const IMMOBILIER = 'IMMOBILIER';
    const RECHERCHE = 'RECHERCHE';
    const VENTES = 'VENTES';
    const ASSISTANCE = 'ASSISTANCE';
    const AUTRES = 'AUTRES';
}
